unit TestmRepeatorRecord;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.Classes, System.SysUtils, mRepeator,
  System.Generics.Collections;

type
  // Test methods for class TSimpleRepeator
  TOrder = (oOne = 0, oTwo, oThree, oFour);

  TestTSimpleRepeator = class(TTestCase)
  strict private
    FRepeator: TSimpleRepeator<TOrder>;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestInitAndCheckCount;
    procedure TestInitAndCurrentValue;
    procedure TestNext;
    procedure TestNextAndCheckPostion;
    procedure TestMovePosByIdx;
    procedure TestMovePosBy;
    procedure TestCurrentByPosition;
    procedure TestEof;
    procedure TestEofBySetPosition;
    procedure TestEofByCallNext;
    procedure TestAdd;
    procedure TestAddSameItem;
    procedure TestRemove;
    procedure TestRemoveNotExists;
    procedure TestExist;
    procedure TestNotExist;
  end;

implementation

procedure TestTSimpleRepeator.SetUp;
begin
  FRepeator := TSimpleRepeator<TOrder>.Create;
end;

procedure TestTSimpleRepeator.TearDown;
begin
  FRepeator.Free;
  FRepeator := nil;
end;

procedure TestTSimpleRepeator.TestInitAndCheckCount;
var
  AItems: TOrder;
begin
  FRepeator.Init([oOne, oTwo, oThree]);
  CheckEquals(3, FRepeator.Count);
end;

procedure TestTSimpleRepeator.TestMovePosBy;
var
  ReturnValue: TOrder;
  i: Integer;
begin
  FRepeator.Init([oOne, oTwo, oThree]);
  for i := 0 to FRepeator.Count - 1 do
  begin
    FRepeator.PosBy := TOrder(i);
    ReturnValue := FRepeator.Current;
    CheckTrue(TOrder(i) = ReturnValue);
  end;
end;

procedure TestTSimpleRepeator.TestMovePosByIdx;
var
  ReturnValue: TOrder;
  i: Integer;
begin
  FRepeator.Init([oOne, oTwo, oThree]);
  for i := 0 to FRepeator.Count - 1 do
  begin
    FRepeator.PosByIdx := i;
    ReturnValue := FRepeator.Current;
    CheckTrue(TOrder(i) = ReturnValue);
  end;
end;

procedure TestTSimpleRepeator.TestNext;
var
  ReturnValue: TOrder;
begin
  FRepeator.Init([oOne, oTwo, oThree]);
  ReturnValue := FRepeator.Next;
  CheckTrue(oTwo = ReturnValue);
end;

procedure TestTSimpleRepeator.TestNextAndCheckPostion;
var
  LItem: TOrder;
  ReturnValue: Integer;
begin
  FRepeator.Init([oOne, oTwo, oThree]);

  LItem := FRepeator.Next;
  ReturnValue := FRepeator.PosByIdx;
  CheckEquals(Integer(LItem), ReturnValue);
  CheckEquals(1, ReturnValue);
end;

procedure TestTSimpleRepeator.TestNotExist;
var
  LExists: Boolean;
begin
  FRepeator.Init([oOne, oTwo, oThree]);
  LExists := FRepeator.Exists(oFour);
  CheckEquals(False, LExists);
end;

procedure TestTSimpleRepeator.TestRemove;
var
  LIdx: Integer;
begin
  FRepeator.Init([oOne, oTwo, oThree]);
  LIdx := FRepeator.Remove(oThree);
  CheckEquals(2, LIdx);
end;

procedure TestTSimpleRepeator.TestRemoveNotExists;
var
  LIdx: Integer;
begin
  FRepeator.Init([oOne, oTwo, oThree]);
  LIdx := FRepeator.Remove(oFour);
  CheckEquals(-1, LIdx);
end;

procedure TestTSimpleRepeator.TestInitAndCurrentValue;
var
  Return: TOrder;
begin
  FRepeator.Init([oOne, oTwo, oThree]);
  Return := FRepeator.Current;
  CheckTrue(oOne = Return);
end;

procedure TestTSimpleRepeator.TestAdd;
var
  LCnt: Integer;
begin
  FRepeator.Init([oOne, oTwo]);
  LCnt := FRepeator.Add(oThree);
  CheckEquals(2, LCnt);
end;

procedure TestTSimpleRepeator.TestAddSameItem;
var
  LCnt: Integer;
begin
  FRepeator.Init([oOne, oTwo]);
  LCnt := FRepeator.Add(oTwo);
  CheckEquals(1, LCnt);
end;

procedure TestTSimpleRepeator.TestCurrentByPosition;
var
  ReturnValue: TOrder;
  i: Integer;
begin
  FRepeator.Init([oOne, oTwo, oThree]);
  for i := 0 to FRepeator.Count - 1 do
  begin
    FRepeator.PosByIdx := i;
    CheckTrue(TOrder(i) = FRepeator.Current);
  end;
end;

procedure TestTSimpleRepeator.TestEof;
var
  ReturnValue: Boolean;
begin
  FRepeator.Init([oOne, oTwo, oThree]);
  ReturnValue := FRepeator.Eof;
  CheckFalse(ReturnValue);
end;

procedure TestTSimpleRepeator.TestEofByCallNext;
var
  ReturnValue: Boolean;
begin
  FRepeator.Init([oOne, oTwo, oThree]);
  FRepeator.Next;
  FRepeator.Next;
  ReturnValue := FRepeator.Eof;
  CheckTrue(ReturnValue);
end;

procedure TestTSimpleRepeator.TestEofBySetPosition;
var
  ReturnValue: Boolean;
begin
  FRepeator.Init([oOne, oTwo, oThree]);
  FRepeator.PosByIdx := FRepeator.Count - 1;
  ReturnValue := FRepeator.Eof;
  CheckTrue(ReturnValue);
end;

procedure TestTSimpleRepeator.TestExist;
var
  LExists: Boolean;
begin
  FRepeator.Init([oOne, oTwo, oThree]);
  LExists := FRepeator.Exists(oOne);
  CheckEquals(True, LExists);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSimpleRepeator.Suite);
end.
